apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      name: user-api
      labels:
        app: user-api
    spec:
      initContainers:
        - name: initialize-db
          image: mysql/mysql-server:8.0
          envFrom:
            - secretRef:
                name: mysql-secret
          command:
            - sh
            - -c
            - |
              until mysql -u $rootUser --password=$rootPassword -h mysql -e 'show databases;'
              do
                echo "Waiting for mysql"
                sleep 3
              done
              mysql -u $rootUser --password=$rootPassword -h mysql \
                -e 'CREATE DATABASE IF NOT EXISTS user_api;'
      containers:
        - name: user-api
          image: tobiaszimmer/user-api:v6
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: dbHost
                  name: mysql-configmap
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: dbName
                  name: mysql-configmap
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: dbUsername
                  name: mysql-configmap
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: dbPassword
                  name: mysql-configmap
      restartPolicy: Always
