apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      name: user-api
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: tobiaszimmer/user-api:v6
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: dbHost
                  name: mysql-configmap
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: dbName
                  name: mysql-configmap
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: dbUsername
                  name: mysql-configmap
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: dbPassword
                  name: mysql-configmap
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: user-api
spec:
  selector:
    app: user-api
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
