apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  labels:
    app: mysql-client
spec:
  containers:
    - name: mysql-client
      image: mysql/mysql-server:8.0
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
