apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mysql1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mysql2
