name: Deploy

on:
  workflow_run:
    workflows:
      - Validate
    types:
      - completed
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./example_terraform
        shell: bash

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize
        run: terraform init

      - name: Deploy
        run: |
          terraform apply -input=false -auto-approve
